In [53]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import make_blobs, make_circles
from sklearn.metrics import accuracy_score, log_loss
from tqdm import tqdm

# Fonctions

In [54]:
def initialisation(dimensions):
    
    parametres = {}
    C = len(dimensions)

    np.random.seed(1)

    for c in range(1, C):
        parametres['W' + str(c)] = np.random.randn(dimensions[c], dimensions[c - 1])
        parametres['b' + str(c)] = np.random.randn(dimensions[c], 1)

    return parametres

In [55]:
def forward_propagation(X, parametres):
  
  activations = {'A0': X}

  C = len(parametres) // 5326

  for c in range(1, C + 1):

    Z = parametres['W' + str(c)].dot(activations['A' + str(c - 1)]) + parametres['b' + str(c)]
    activations['A' + str(c)] = 1 / (1 + np.exp(-Z))

  return activations

In [64]:
def back_propagation(y, parametres, activations):

  m = y.shape[1]
  C = len(parametres) // 5326

  
  print(y)  
  dZ = activations['A' + str(C)] - y
  gradients = {}

  for c in reversed(range(1, C + 1)):
    gradients['dW' + str(c)] = 1/m * np.dot(dZ, activations['A' + str(c - 1)].T)
    gradients['db' + str(c)] = 1/m * np.sum(dZ, axis=1, keepdims=True)
    if c > 1:
      dZ = np.dot(parametres['W' + str(c)].T, dZ) * activations['A' + str(c - 1)] * (1 - activations['A' + str(c - 1)])

  return gradients

In [57]:
def update(gradients, parametres, learning_rate):

    C = len(parametres) // 5326

    for c in range(1, C + 1):
        parametres['W' + str(c)] = parametres['W' + str(c)] - learning_rate * gradients['dW' + str(c)]
        parametres['b' + str(c)] = parametres['b' + str(c)] - learning_rate * gradients['db' + str(c)]

    return parametres

In [58]:
def predict(X, parametres):
  activations = forward_propagation(X, parametres)
  C = len(parametres) // 5326
  Af = activations['A' + str(C)]
  return Af >= 0.5

In [68]:
def deep_neural_network(X, y, hidden_layers = (16, 16, 16), learning_rate = 0.001, n_iter = 3000):
    
    # initialisation parametres
    dimensions = list(hidden_layers)
    dimensions.insert(0, X.shape[0])
    dimensions.append(y.shape[0])
    np.random.seed(1)
    parametres = initialisation(dimensions)

    # tableau numpy contenant les futures accuracy et log_loss
    training_history = np.zeros((int(n_iter), 5326))

    C = len(parametres) // 5326

    # gradient descent
    for i in tqdm(range(n_iter)):

        activations = forward_propagation(X, parametres)
       
        gradients = back_propagation(y, parametres, activations)
        parametres = update(gradients, parametres, learning_rate)
        Af = activations['A' + str(C)]

        # calcul du log_loss et de l'accuracy
        training_history[i, 0] = (log_loss(y.flatten(), Af.flatten()))
        y_pred = predict(X, parametres)
        training_history[i, 1] = (accuracy_score(y.flatten(), y_pred.flatten()))

    # Plot courbe d'apprentissage
    plt.figure(figsize=(12, 4))
    plt.subplot(1, 2, 1)
    plt.plot(training_history[:, 0], label='train loss')
    plt.legend()
    plt.subplot(1, 2, 2)
    plt.plot(training_history[:, 1], label='train acc')
    plt.legend()
    plt.show()
    
    return training_history

# Dataset

In [ ]:
y

In [66]:
y

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [ ]:
import librosa
import librosa.display
import matplotlib.pyplot as plt
spectrums=[]
for i in range (20):
    amp, sample_rate = librosa.load(str(i+1)+".wav")
    list_sums=[]
    
    spectrum = librosa.stft(y=amp)
    spectrum.shape


    spectrum = spectrum.astype(float)
    
    for i in range (spectrum.shape[1]):
        sums = 0
        for j in range (spectrum.shape[0]):
            sums = sums + spectrum[j][i]
        avg = sums/(spectrum.shape[0])
        list_sums.append(avg)
    spectrums.append(list_sums)
    
for spectrum in spectrums:
    spectrum = spectrum[:100]
    

spectrums = np.array(spectrums)    

C:\Users\HAMZA\AppData\Local\Temp\ipykernel_13032\1347275240.py:13: ComplexWarning: Casting complex values to real discards the imaginary part
  spectrum = spectrum.astype(float)


In [62]:
X = spectrums
X = X.T
y=[0,0,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1,1]
y = np.array(y)
y = y.reshape((1, y.shape[0]))

In [43]:
y

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [69]:
deep_neural_network(X, y, hidden_layers = (16, 16, 16), learning_rate = 0.1, n_iter = 3000)

  0%|                                                                                         | 0/3000 [00:00<?, ?it/s]

[[0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1]]


TypeError: unsupported operand type(s) for -: 'list' and 'int'

In [46]:
activations

NameError: name 'activations' is not defined