Ouverture BDD

In [10]:
import numpy as np
from tensorflow import keras
import joblib
from sklearn.ensemble import RandomForestClassifier

In [6]:
with open('npy/X_train_2.npy','rb') as f:
    X_train = np.load(f)

with open('npy/X_test_2.npy','rb') as f:
    X_test = np.load(f)

with open('npy/y_train_2.npy','rb') as f:
    y_train = np.load(f)

with open('npy/y_test_2.npy','rb') as f:
    y_test = np.load(f)

In [17]:
X_train_t = np.array([k.transpose() for k in X_train])
X_train_t.shape

(2086, 100, 1025)

In [18]:
X_test_t = np.array([k.transpose() for k in X_test])
X_test_t.shape

(331, 100, 1025)

In [69]:
y_test

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,

In [73]:
Y_test_nn = []
for k in y_test:
    if k==0:
        Y_test_nn.append([1,0])
    else:
        Y_test_nn.append([0,1])
        
Y_test_nn = np.array(Y_test_nn)
Y_train_nn = []
for k in y_train:
    if k==0:
        Y_train_nn.append([1,0])
    else:
        Y_train_nn.append([0,1])
Y_train_nn = np.array(Y_train_nn)        


Ouverture des modèles

In [11]:
NN = keras.models.load_model('nn.h5')
LSTM = keras.models.load_model('LSTM.h5')
CNN_1 = keras.models.load_model('Conv2D_3.h5')
CNN_2 = keras.models.load_model('Conv2D_good_for_both.h5')
rf = joblib.load("./rf.joblib")




Création de la base de donnée pour l'aggrégateur

In [16]:
X_train[0].shape

(1025, 100)

In [33]:
def signe(x):
    if x>0:
        return 1
    else:
        return -1

def has_voice_vote(X_batch,NNmodel):
    results = NNmodel.predict(X_batch,verbose=0)
    vote = 0
    for res in results:
        confiance = res[0]-res[1]
        if confiance>0:
            vote += 1
    proportion = vote/len(X_batch)
    #print(vote)
    if proportion > 0.5:
        return 1
    else:
        return 0

In [34]:
X_NN = []
for k in X_train_t:
    res = has_voice_vote(k,NN)
    X_NN.append(res)
print(X_NN)

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

In [55]:
X_LSTM_train = LSTM.predict(X_train_t)
X_LSTM_train = np.array([k[0] for k in X_LSTM_train])

X_LSTM_test = LSTM.predict(X_test_t)
X_LSTM_test = np.array([k[0] for k in X_LSTM_test])

11/11 [==============================] - 4s 340ms/step


In [56]:
X_CNN_1_train = CNN_1.predict(X_train)
X_CNN_1_train = np.array([k[0] for k in X_CNN_1_train])

X_CNN_1_test = CNN_1.predict(X_test)
X_CNN_1_test = np.array([k[0] for k in X_CNN_1_test])

11/11 [==============================] - 1s 131ms/step


In [57]:
X_CNN_2_train = CNN_2.predict(X_train)
X_CNN_2_train = np.array([k[0] for k in X_CNN_2_train])

X_CNN_2_test = CNN_2.predict(X_test)
X_CNN_2_test = np.array([k[0] for k in X_CNN_2_test])

11/11 [==============================] - 2s 210ms/step


In [59]:
X_train_agg = np.array([[X_LSTM_train[k],X_CNN_1_train[k],X_CNN_2_train[k]] for k in range(len(X_LSTM_train))])
X_test_agg = np.array([[X_LSTM_test[k],X_CNN_1_test[k],X_CNN_2_test[k]] for k in range(len(X_LSTM_test))])

In [60]:
print(X_train_agg)

[[0.08311042 1.         1.        ]
 [0.9859758  1.         1.        ]
 [0.08311042 1.         1.        ]
 ...
 [0.98597544 1.         1.        ]
 [0.92945725 1.         1.        ]
 [0.92945725 1.         1.        ]]


In [61]:
print(X_test_agg)

[[8.31104219e-02 0.00000000e+00 0.00000000e+00]
 [8.31104219e-02 0.00000000e+00 0.00000000e+00]
 [8.31104219e-02 0.00000000e+00 0.00000000e+00]
 [8.31104219e-02 0.00000000e+00 0.00000000e+00]
 [8.31104219e-02 0.00000000e+00 0.00000000e+00]
 [8.31104219e-02 0.00000000e+00 0.00000000e+00]
 [8.31104219e-02 0.00000000e+00 0.00000000e+00]
 [2.48713121e-02 0.00000000e+00 0.00000000e+00]
 [2.51352116e-02 0.00000000e+00 6.45184262e-09]
 [2.48713121e-02 0.00000000e+00 1.00000000e+00]
 [2.48713121e-02 0.00000000e+00 3.44380452e-21]
 [8.31104219e-02 3.20881992e-26 4.61093522e-23]
 [8.31104219e-02 0.00000000e+00 0.00000000e+00]
 [2.48713121e-02 0.00000000e+00 0.00000000e+00]
 [2.48713121e-02 0.00000000e+00 1.00000000e+00]
 [2.48713121e-02 0.00000000e+00 1.00000000e+00]
 [2.48713121e-02 0.00000000e+00 0.00000000e+00]
 [2.48713121e-02 0.00000000e+00 0.00000000e+00]
 [8.31104219e-02 0.00000000e+00 0.00000000e+00]
 [8.31104219e-02 0.00000000e+00 0.00000000e+00]
 [8.31104219e-02 0.00000000e+00 0.000000

In [62]:
X_train_agg.shape

(2086, 3)

In [64]:
rf_agg = RandomForestClassifier(n_jobs=-1)
rf_agg.fit(X_train_agg,y_train)


from sklearn.metrics import accuracy_score

pred = rf_agg.predict(X_test_agg)
accuracy_score(pred,y_test)

0.9123867069486404

In [65]:
def model():
    model = Sequential()
    model.add(Dense(8,input_dim=3, activation='relu'))
    model.add(Dense(8))
    model.add(Dense(2, activation='softmax'))
    model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
    return model

In [74]:
nn_agg = model()
nn_agg.fit(X_train_agg, Y_train_nn, epochs=20, batch_size=64)

Epoch 1/20
33/33 [==============================] - 0s 1ms/step - loss: 0.6487 - accuracy: 0.6563
Epoch 2/20
33/33 [==============================] - 0s 907us/step - loss: 0.6086 - accuracy: 0.6563
Epoch 3/20
33/33 [==============================] - 0s 1ms/step - loss: 0.5687 - accuracy: 0.6563
Epoch 4/20
33/33 [==============================] - 0s 970us/step - loss: 0.5267 - accuracy: 0.6568
Epoch 5/20
33/33 [==============================] - 0s 970us/step - loss: 0.4830 - accuracy: 0.6563
Epoch 6/20
33/33 [==============================] - 0s 938us/step - loss: 0.4342 - accuracy: 0.7478
Epoch 7/20
33/33 [==============================] - 0s 970us/step - loss: 0.3826 - accuracy: 0.9223
Epoch 8/20
33/33 [==============================] - 0s 970us/step - loss: 0.3287 - accuracy: 0.9233
Epoch 9/20
33/33 [==============================] - 0s 970us/step - loss: 0.2828 - accuracy: 0.9233
Epoch 10/20
33/33 [==============================] - 0s 970us/step - loss: 0.2493 - accuracy: 0.9238
Epo

In [77]:
y_pred = nn_agg.predict(X_test_agg)
y_pred_aux = []
for k in y_pred:
    if k[0]>k[1]:
        y_pred_aux.append([1,0])
    else:
        y_pred_aux.append([0,1])

from sklearn.metrics import accuracy_score
a = accuracy_score(y_pred_aux,Y_test_nn)
print('Accuracy is:', a*100)

11/11 [==============================] - 0s 801us/step
Accuracy is: 92.14501510574019
